package safranil.minecraft.miroa;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.util.Properties;

class OptionSaver {
    private final File file;
    private final Properties properties;

    OptionSaver(File file) {
        this.file = file;
        properties = new Properties();
        if (file.exists()) {
            load();
        }

    }

    void set(String key, String value) {
        properties.setProperty(key, value);
        save();
    }

    String get(String key) {
        return properties.getProperty(key);
    }

    boolean remove(String key) {
        if (properties.remove(key) != null) {
            save();
            return true;
        }
        return false;
    }

    private void save() {
        try {
            properties.store(new BufferedWriter(new FileWriter(this.file)), "Generated by Miroa Launcher");
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }

    private void load() {
        try {
            properties.load(new FileInputStream(this.file));
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
}
