/**
 * This file is part of Miroa Launcher.
 * Copyright (C) 2016 David Cachau <dev@safranil.fr>
 *
 * Miroa Launcher is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * Miroa Launcher is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Miroa Launcher.  If not, see <http://www.gnu.org/licenses/>.
 */
package safranil.minecraft.miroa;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.util.Properties;

/**
 * Save some option in a .properties file
 */
class OptionSaver {
    private final File file;
    private final Properties properties;

    OptionSaver(File file) {
        this.file = file;
        properties = new Properties();
        if (file.exists()) {
            load();
        }

    }

    void set(String key, String value) {
        properties.setProperty(key, value);
        save();
    }

    String get(String key) {
        return properties.getProperty(key);
    }

    boolean remove(String key) {
        if (properties.remove(key) != null) {
            save();
            return true;
        }
        return false;
    }

    private void save() {
        try {
            properties.store(new BufferedWriter(new FileWriter(this.file)), "Generated by Miroa Launcher");
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }

    private void load() {
        try {
            properties.load(new FileInputStream(this.file));
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
}
