package safranil.minecraft.miroa;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.util.Properties;

public class OptionSaver {
    private File file;
    private Properties properties;

    public OptionSaver(File file) {
        this.file = file;
        properties = new Properties();
        if (file.exists()) {
            load();
        }

    }

    public void set(String key, String value) {
        properties.setProperty(key, value);
        save();
    }

    public String get(String key) {
        return properties.getProperty(key);
    }

    public String get(String key, String def) {
        String value = properties.getProperty(key);
        return value == null ? def : value;
    }

    public boolean remove(String key) {
        if (properties.remove(key) != null) {
            save();
            return true;
        }
        return false;
    }

    public void save() {
        try {
            properties.store(new BufferedWriter(new FileWriter(this.file)), "Generated by Miroa Launcher");
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }

    public void load() {
        try {
            properties.load(new FileInputStream(this.file));
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
}
